### ISSUE TITLE
Optimize travis-ci integration

### ISSUE THREAD

**Issue by henri-hulski** [morepath/morepath#398]
We can optimize the travis integration by switching to the new container-based infrastructure.
It would then also be possible to use the travis cache for pip.
The code for `.travis.yml` could look something like:
```yaml
sudo: false
cache: pip
before_install:
    - pip install --upgrade pip setuptools
```
